<a href="https://colab.research.google.com/github/shazinmuhammed07/placement_prediction/blob/main/Placement_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PROJECT

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [60]:
df = pd.read_csv("/content/placementdata.csv")

In [61]:
df.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

In [62]:
df.isnull().sum()

StudentID                    0
CGPA                         0
Internships                  0
Projects                     0
Workshops/Certifications     0
AptitudeTestScore            0
SoftSkillsRating             0
ExtracurricularActivities    0
PlacementTraining            0
SSC_Marks                    0
HSC_Marks                    0
PlacementStatus              0
dtype: int64

In [63]:
df.shape

(10000, 12)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  10000 non-null  int64
 1   CGPA                       10000 non-null  float64
 2   Internships                10000 non-null  int64
 3   Projects                   10000 non-null  int64
 4   Workshops/Certifications   10000 non-null  int64
 5   AptitudeTestScore          10000 non-null  int64
 6   SoftSkillsRating           10000 non-null  float64
 7   ExtracurricularActivities  10000 non-null  object
 8   PlacementTraining          10000 non-null  object
 9   SSC_Marks                  10000 non-null  int64
 10  HSC_Marks                  10000 non-null  int64
 11  PlacementStatus            10000 non-null  object
dtypes: float64(2), int64(7), object(3)
memory usage: 937.6+ KB

In [65]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in ['PlacementStatus','PlacementTraining','ExtracurricularActivities','Internships','Projects','Workshops/Certifications']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop('PlacementStatus',axis=1)
y = df['PlacementStatus']
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standard Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC,LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report



models = {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier(),
}

# Train and Evaluate Models
results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = accuracy
    print(f"{name} Accuracy: {accuracy:.4f}")
    print(classification_report(y_test, y_pred))
    print("-" * 60)

Random Forest Accuracy: 0.7885
              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1172
           1       0.75      0.73      0.74       828

    accuracy                           0.79      2000
   macro avg       0.78      0.78      0.78      2000
weighted avg       0.79      0.79      0.79      2000

------------------------------------------------------------
Logistic Regression Accuracy: 0.7935
              precision    recall  f1-score   support

           0       0.83      0.81      0.82      1172
           1       0.74      0.77      0.75       828

    accuracy                           0.79      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.79      0.79      0.79      2000

------------------------------------------------------------
Support Vector Machine Accuracy: 0.7950
              precision    recall  f1-score   support

           0       0.82      0.83      0.83      1172
           1       0.76      0.75      0.75       828

    accuracy                           0.80      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.79      0.80      0.79      2000

------------------------------------------------------------
K-Nearest Neighbors Accuracy: 0.7710
              precision    recall  f1-score   support

           0       0.80      0.81      0.81      1172
           1       0.73      0.71      0.72       828

    accuracy                           0.77      2000
   macro avg       0.76      0.76      0.76      2000
weighted avg       0.77      0.77      0.77      2000

------------------------------------------------------------
Naive Bayes Accuracy: 0.7935
              precision    recall  f1-score   support

           0       0.85      0.79      0.82      1172
           1       0.73      0.80      0.76       828

    accuracy                           0.79      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.80      0.79      0.79      2000

------------------------------------------------------------
Decision Tree Accuracy: 0.7205
              precision    recall  f1-score   support

           0       0.77      0.75      0.76      1172
           1       0.66      0.67      0.67       828

    accuracy                           0.72      2000
   macro avg       0.71      0.71      0.71      2000
weighted avg       0.72      0.72      0.72      2000

------------------------------------------------------------

#### Random Forest Classifier

In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print(f"Random Forest Accuracy: {accuracy_rf:.4f}")
print(classification_report(y_test, y_pred_rf))
print("-" * 60)

Random Forest Accuracy: 0.7935
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      1172
           1       0.76      0.73      0.75       828

    accuracy                           0.79      2000
   macro avg       0.79      0.78      0.79      2000
weighted avg       0.79      0.79      0.79      2000

------------------------------------------------------------

#### Logistic Regression

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model_lr = LogisticRegression(random_state=42, solver='liblinear') # Added solver to avoid warning
model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)
accuracy_lr = accuracy_score(y_test, y_pred_lr)

print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")
print(classification_report(y_test, y_pred_lr))
print("-" * 60)

Logistic Regression Accuracy: 0.7935
              precision    recall  f1-score   support

           0       0.83      0.81      0.82      1172
           1       0.74      0.77      0.75       828

    accuracy                           0.79      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.79      0.79      0.79      2000

------------------------------------------------------------

#### Support Vector Machine

In [70]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

model_svc = SVC(random_state=42)
model_svc.fit(X_train, y_train)
y_pred_svc = model_svc.predict(X_test)
accuracy_svc = accuracy_score(y_test, y_pred_svc)

print(f"Support Vector Machine Accuracy: {accuracy_svc:.4f}")
print(classification_report(y_test, y_pred_svc))
print("-" * 60)

Support Vector Machine Accuracy: 0.7950
              precision    recall  f1-score   support

           0       0.82      0.83      0.83      1172
           1       0.76      0.75      0.75       828

    accuracy                           0.80      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.79      0.80      0.79      2000

------------------------------------------------------------

#### K-Nearest Neighbors

In [71]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

model_knn = KNeighborsClassifier()
model_knn.fit(X_train, y_train)
y_pred_knn = model_knn.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)

print(f"K-Nearest Neighbors Accuracy: {accuracy_knn:.4f}")
print(classification_report(y_test, y_pred_knn))
print("-" * 60)

K-Nearest Neighbors Accuracy: 0.7710
              precision    recall  f1-score   support

           0       0.80      0.81      0.81      1172
           1       0.73      0.71      0.72       828

    accuracy                           0.77      2000
   macro avg       0.76      0.76      0.76      2000
weighted avg       0.77      0.77      0.77      2000

------------------------------------------------------------

#### Naive Bayes

In [72]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

model_gnb = GaussianNB()
model_gnb.fit(X_train, y_train)
y_pred_gnb = model_gnb.predict(X_test)
accuracy_gnb = accuracy_score(y_test, y_pred_gnb)

print(f"Naive Bayes Accuracy: {accuracy_gnb:.4f}")
print(classification_report(y_test, y_pred_gnb))
print("-" * 60)

Naive Bayes Accuracy: 0.7935
              precision    recall  f1-score   support

           0       0.85      0.79      0.82      1172
           1       0.73      0.80      0.76       828

    accuracy                           0.79      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.80      0.79      0.79      2000

------------------------------------------------------------

#### Decision Tree Classifier

In [73]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)
y_pred_dt = model_dt.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)

print(f"Decision Tree Accuracy: {accuracy_dt:.4f}")
print(classification_report(y_test, y_pred_dt))
print("-" * 60)

Decision Tree Accuracy: 0.7250
              precision    recall  f1-score   support

           0       0.77      0.76      0.76      1172
           1       0.67      0.67      0.67       828

    accuracy                           0.72      2000
   macro avg       0.72      0.72      0.72      2000
weighted avg       0.73      0.72      0.73      2000

------------------------------------------------------------